# Generated by Django 5.0.6 on 2024-06-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingAPI_app', '0002_poll_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='title',
            new_name='question',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='pollingAPI_app.poll')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pollingAPI_app.choice'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
