# Generated by Django 5.0.6 on 2024-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingAPI_app', '0003_remove_response_question_rename_title_poll_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
