# Generated by Django 5.0.6 on 2024-06-14 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingAPI_app', '0006_alter_choice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='users_voted',
            field=models.ManyToManyField(related_name='polls_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
